name: Build Tweak

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Checkout theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Install dependencies
        run: |
          brew install ldid xz

      - name: Build package
        run: |
          export THEOS=$(pwd)/theos
          export PATH=$THEOS/bin:$PATH
          make package

      - name: Upload dylib
        uses: actions/upload-artifact@v4   # ← J'AI BIEN REMPLACÉ v3 PAR v4 ICI
        with:
          name: ESPBox_dylib
          path: .theos/obj/debug/*.dylib
